version: '3.8'

services:
  postgres_db:
    image: postgres:latest
    container_name: fitness_postgres_container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=fitness123  
      - POSTGRES_DB=FitnessAppDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: